[build]
builder = "nixpacks"
buildCommand = "export NODE_OPTIONS=--max_old_space_size=1024 && rm -rf build dist && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
