services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    plan: starter
    runtime: node
    buildCommand: npm install
    startCommand: node test-server.js
    envVars:
      - key: NODE_ENV
        value: production
