# Render deployment configuration
version: 1

services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci --only=production && cd sheets-connector-backend && npm ci --only=production
    startCommand: npm start
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
