services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    plan: starter
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
