services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    plan: starter
    runtime: node
    buildCommand: cd sheets-connector-backend && npm install
    startCommand: cd sheets-connector-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
