# Render deployment configuration
version: 1

services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
