# Render deployment configuration
version: 1

services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci --only=production && cd sheets-connector-backend && npm ci --only=production && npm run build
    startCommand: npm start
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
