services:
  - type: web
    name: datapingo-sheets-connector
    env: node
    plan: starter
    runtime: node
    buildCommand: cd sheets-connector-backend && npm install
    startCommand: cd sheets-connector-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        value: "placeholder"
      - key: GOOGLE_CLIENT_SECRET
        value: "placeholder"
      - key: GOOGLE_REDIRECT_URI
        value: "https://datapingo-sheets-connector.onrender.com/auth/callback"
      - key: SLACK_BOT_TOKEN
        value: "placeholder"
      - key: SLACK_SIGNING_SECRET
        value: "placeholder"
